services:
  - type: web
    name: wanderlust-project
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://wanderlust-project.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ATLASDB_URL
        sync: false
      - key: SESSION_SECRET
        sync: false 